name: "Plan: the tfmake way"

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read
  pull-requests: write

jobs:
  plan:
    runs-on: ubuntu-20.04
    name: Plan

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_wrapper: false

    - name: Get all changed files
      id: changed_files
      uses: tj-actions/changed-files@v41
      with:
        diff_relative: true

    - name: tfmake install
      uses: tfmake/tfmake-install-action@main
      with:
        tfmake_version: main

    - name: tfmake execution
      uses: tfmake/tfmake-action@main
      with:
        tfmake_context: plan
        touch_files: ${{ steps.changed_files.outputs.all_modified_files }}
        tfmake_summary_title: "Terraform Plan"
        pull_request_number: ${{ github.event.pull_request.number }}
